# Generated by Django 6.0 on 2026-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_consultation_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('sales', 'Sales'), ('patient', 'Patient')], default='patient', max_length=10),
        ),
    ]
