# Generated by Django 6.0 on 2026-02-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_meeting_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
