# Generated by Django 6.0 on 2026-02-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_hours', to='consultation.clinic'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('semen_collection', 'Semen Collection'), ('pathology', 'Pathology'), ('ultrasound', 'Ultrasound'), ('surgery', 'Surgery'), ('sales_meeting', 'Sales Meeting')], default='consultation', max_length=30),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('CONSULT', 'Consultation'), ('SALES_MEETING', 'Sales Meeting'), ('SALES', 'Sales'), ('DEMO', 'Demo')], default='CONSULT', max_length=20),
        ),
    ]
